__include__: [
  '../dataset/kitti_detection_for_eval.yml',
  '../runtime.yml',
  './include/dataloader_custom_T4.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd_custom.yml',
]


output_dir: ./output/rtdetrv2_kitti

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5
  encoder_type: VimEncoder
  upsampling_type: sub_pixel
  num_encoder_layers: 3


RTDETRTransformerv2:
  num_layers: 3


epoches: 2

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 1
  collate_fn:
    scales: ~