__include__: [
  '../dataset/kitti_detection.yml',
  '../runtime.yml',
  './include/custom_dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd_custom.yml',
]


output_dir: ./output/rtdetrv2_r18vd_120e_coco


PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  encoder_type: 'VimEncoder'
  upsampling_type: 'sub_pixel'
  use_encoder_idx: [2]
  num_encoder_layers: 3
  in_channels: [128, 256, 512]
  hidden_dim: 256
  dim_feedforward: 1024
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3


epoches: 120 

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 117
  collate_fn:
    scales: ~